# For the 'http-trigger' helm chart
components:
  - name: petstore-mcp
    image: ghcr.io/cosmonic-labs/petstore-mcp-server:v0.3.0

ingress:
  host: "petstore-mcp.localhost.cosmonic.sh"

pathNote: "/v1/mcp"